// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCLrqnQEHopE9xJrE9sLyIMld7SibWOac',
    appId: '1:340084891891:web:8f3a7d3e371fe86db7d786',
    messagingSenderId: '340084891891',
    projectId: 'aksesuar-kedi-oto',
    authDomain: 'aksesuar-kedi-oto.firebaseapp.com',
    storageBucket: 'aksesuar-kedi-oto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHpV8A1I8DWxd3JEQgOuPUnjdZvaeckA',
    appId: '1:340084891891:android:ef8bef355b4466efb7d786',
    messagingSenderId: '340084891891',
    projectId: 'aksesuar-kedi-oto',
    storageBucket: 'aksesuar-kedi-oto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4KRrsUUmf-D4y4qgGu5f-BTMin8vTmNk',
    appId: '1:340084891891:ios:e4903b909edf012fb7d786',
    messagingSenderId: '340084891891',
    projectId: 'aksesuar-kedi-oto',
    storageBucket: 'aksesuar-kedi-oto.appspot.com',
    iosBundleId: 'com.example.kediOtoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4KRrsUUmf-D4y4qgGu5f-BTMin8vTmNk',
    appId: '1:340084891891:ios:6889f1164b234952b7d786',
    messagingSenderId: '340084891891',
    projectId: 'aksesuar-kedi-oto',
    storageBucket: 'aksesuar-kedi-oto.appspot.com',
    iosBundleId: 'com.example.kediOtoApp.RunnerTests',
  );
}
